version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "error-template"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cbee0m55iz1n"
s3_prefix = "error-template"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvType=\"stage\""
